"""Reader for Tecplot binary .plt files generated by q2plt.f90.

The writer in q2plt.f90 uses Fortran stream/unformatted output and writes:
1) file header and variable names
2) zone metadata
3) block-formatted variable data arrays
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO

import numpy as np


@dataclass
class TecplotZone:
	"""Single zone data container."""

	ni: int
	nj: int
	nk: int
	data: dict[str, np.ndarray]


@dataclass
class TecplotPlt:
	"""Parsed Tecplot file payload."""

	title: str
	variable_names: list[str]
	zones: list[TecplotZone]
	ndim: int


def _read_exact(file_obj: BinaryIO, nbytes: int) -> bytes:
	data = file_obj.read(nbytes)
	if len(data) != nbytes:
		raise EOFError(f"Unexpected end of file: expected {nbytes} bytes, got {len(data)}")
	return data


def _read_i4(file_obj: BinaryIO) -> int:
	return np.frombuffer(_read_exact(file_obj, 4), dtype="<i4", count=1)[0].item()


def _read_f4(file_obj: BinaryIO) -> float:
	return np.frombuffer(_read_exact(file_obj, 4), dtype="<f4", count=1)[0].item()


def _read_zero_terminated_char_i4_stream(file_obj: BinaryIO) -> str:
	chars: list[str] = []
	while True:
		code = _read_i4(file_obj)
		if code == 0:
			break
		chars.append(chr(code))
	return "".join(chars)


def _read_variable_names(file_obj: BinaryIO, num_vars: int) -> list[str]:
	names: list[str] = []
	current: list[str] = []
	while len(names) < num_vars:
		code = _read_i4(file_obj)
		if code == 0:
			names.append("".join(current))
			current = []
			continue
		current.append(chr(code))
	return names


def _read_block_array(
	file_obj: BinaryIO,
	*,
	ni: int,
	nj: int,
	nk: int,
	dtype: np.dtype,
) -> np.ndarray:
	npts = ni * nj * nk
	nbytes = npts * np.dtype(dtype).itemsize
	raw = _read_exact(file_obj, nbytes)
	flat = np.frombuffer(raw, dtype=dtype, count=npts)
	# Fortran loops in q2plt.f90 write i-fastest, then j, then k.
	return flat.reshape((ni, nj, nk), order="F")


def read_plt75(path: str | Path) -> TecplotPlt:
	"""Read a Tecplot binary .plt file produced by original q2plt.f90 (#!TDV75).

	Parameters
	----------
	path:
		File path to a .plt file.

	Returns
	-------
	TecplotPlt
		Parsed header and zone data.
	"""

	file_path = Path(path)
	with file_path.open("rb") as f:
		magic = _read_exact(f, 8)
		if magic != b"#!TDV75 ":
			raise ValueError(f"Unsupported magic number: {magic!r}")

		identifier = _read_i4(f)
		if identifier != 1:
			raise ValueError(f"Unsupported Tecplot identifier: {identifier}")

		title = _read_zero_terminated_char_i4_stream(f)
		num_vars = _read_i4(f)
		variable_names = _read_variable_names(f, num_vars)

		# Zone section. q2plt.f90 writes one zone, but we parse generically.
		zones_meta: list[tuple[int, int, int]] = []
		while True:
			marker = _read_f4(f)
			if not np.isclose(marker, 299.0, rtol=0.0, atol=1e-6):
				# First non-zone marker is data-section marker (357.0).
				if not np.isclose(marker, 357.0, rtol=0.0, atol=1e-6):
					raise ValueError(f"Unexpected marker before data section: {marker}")
				break

			_ = np.frombuffer(_read_exact(f, 7 * 4), dtype="<i4", count=7)
			_iformat = _read_i4(f)
			_zone_color = _read_i4(f)
			ni = _read_i4(f)
			nj = _read_i4(f)
			nk = _read_i4(f)
			zones_meta.append((ni, nj, nk))

		zones: list[TecplotZone] = []
		for ni, nj, nk in zones_meta:
			zone_marker = _read_f4(f)
			if not np.isclose(zone_marker, 299.0, rtol=0.0, atol=1e-6):
				raise ValueError(f"Unexpected zone data marker: {zone_marker}")

			_numrp = _read_i4(f)
			datatypes = [_read_i4(f) for _ in range(num_vars)]

			zone_data: dict[str, np.ndarray] = {}
			for var_name, data_type_code in zip(variable_names, datatypes):
				if data_type_code == 1:
					dtype = np.dtype("<f4")
				elif data_type_code == 2:
					dtype = np.dtype("<f8")
				else:
					raise ValueError(f"Unsupported data type code: {data_type_code}")

				zone_data[var_name] = _read_block_array(
					f,
					ni=ni,
					nj=nj,
					nk=nk,
					dtype=dtype,
				)

			zones.append(TecplotZone(ni=ni, nj=nj, nk=nk, data=zone_data))

		ndim = 3 if len(variable_names) >= 3 and variable_names[2] == "zc" else 2

		return TecplotPlt(
			title=title,
			variable_names=variable_names,
			zones=zones,
			ndim=ndim,
		)


def read_plt(path: str | Path) -> TecplotPlt:
	"""Backward-compatible alias for the TDV75 reader."""

	return read_plt75(path)


if __name__ == "__main__":
	import argparse

	parser = argparse.ArgumentParser(
		description="Read q2plt-generated Tecplot binary files and visualize flow frames"
	)
	parser.add_argument(
		"plt_file",
		type=Path,
		nargs="?",
		help="Path to a single Tecplot .plt file (for quick header inspection)",
	)
	parser.add_argument(
		"--data-path",
		type=Path,
		help="Directory containing Q.*.plt files for interactive visualization",
	)
	parser.add_argument(
		"--dt",
		type=float,
		default=1.0,
		help="Time increment between consecutive frames (default: 1.0)",
	)
	parser.add_argument(
		"--quiver-step",
		type=int,
		default=24,
		help="Subsampling step for quiver arrows (default: 24)",
	)
	parser.add_argument(
		"--frac",
		type=float,
		default=1.414,
		help="Arrow-length factor in grid-spacing units (default: sqrt(2))",
	)
	parser.add_argument(
		"--vort-step",
		type=int,
		default=8,
		help="Subsampling step for vorticity background rendering (default: 8)",
	)
	parser.add_argument(
		"--autoplay",
		action="store_true",
		help="Automatically play frames in a loop",
	)
	parser.add_argument(
		"--fps",
		type=float,
		default=25.0,
		help="Target playback FPS for --autoplay mode (default: 25)",
	)
	parser.add_argument(
		"--no-slider",
		action="store_true",
		help="Disable frame slider to reduce UI overhead in high-speed playback",
	)
	parser.add_argument(
		"--decay",
		type=float,
		default=0.0,
		metavar="MULT",
		help="Append MULT*N extra frames where velocity decays from the last real frame with half-life = total real duration",
	)
	args = parser.parse_args()

	if args.data_path is not None:
		from visualize_flow import visualize_flow

		visualize_flow(
			args.data_path,
			dt=args.dt,
			quiver_step=args.quiver_step,
			frac=args.frac,
			vort_step=args.vort_step,
			autoplay=args.autoplay,
			fps=args.fps,
			show_slider=not args.no_slider,
			decay=args.decay,
		)
	elif args.plt_file is not None:
		parsed = read_plt75(args.plt_file)
		print(f"title={parsed.title}")
		print(f"ndim={parsed.ndim}")
		print(f"variables={parsed.variable_names}")
		for i, zone in enumerate(parsed.zones, start=1):
			print(f"zone[{i}] shape=(ni={zone.ni}, nj={zone.nj}, nk={zone.nk})")
	else:
		parser.error("Provide either a single plt_file or --data-path for interactive visualization.")
