# simple advection
import numpy as np
from scipy.ndimage import map_coordinates
import matplotlib.pyplot as plt

def advect_2d(x, y, u, v, dt):
    """
    Performs Semi-Lagrangian advection on a 2D velocity field.
    
    Parameters:
    x, y  : 2D numpy arrays of the grid coordinates (from np.meshgrid)
    u, v  : 2D numpy arrays of the velocity field components
    dt    : Time step for advection
    
    Returns:
    u_new, v_new : The advected velocity components
    """
    # 1. The Backward Trace
    # Find where the fluid at the current grid points came from dt seconds ago
    x_back = x - u * dt
    y_back = y - v * dt
    
    # 2. Convert physical coordinates to fractional grid indices
    # map_coordinates works on array indices (0, 1, 2.5, etc.), not physical coordinates.
    # We assume a uniform grid generated by np.meshgrid(..., indexing='xy')
    Ny, Nx = x.shape
    
    x_min, x_max = np.min(x), np.max(x)
    y_min, y_max = np.min(y), np.max(y)
    
    dx = (x_max - x_min) / (Nx - 1)
    dy = (y_max - y_min) / (Ny - 1)
    
    # Calculate the fractional index of the source locations
    idx_x = (x_back - x_min) / dx
    idx_y = (y_back - y_min) / dy
    
    # Stack indices. Since numpy arrays are indexed (row, column) -> (y, x)
    indices = np.stack([idx_y, idx_x])
    
    # 3. Interpolate the new velocities
    # order=1 means bilinear interpolation. 
    # mode='nearest' means if we trace a path outside the grid boundaries, 
    # we just grab the velocity of the closest boundary edge.
    u_new = map_coordinates(u, indices, order=1, mode='nearest')
    v_new = map_coordinates(v, indices, order=1, mode='nearest')
    
    return u_new, v_new


# ==========================================
# TEST AND VISUALIZATION
# ==========================================
if __name__ == "__main__":
    # Create a spatial grid from -3 to 3
    grid_size = 100
    x_1d = np.linspace(-3, 3, grid_size)
    y_1d = np.linspace(-3, 3, grid_size)
    x, y = np.meshgrid(x_1d, y_1d)

    # Create a flow field: A strong vortex in the center + a steady wind blowing right
    # Vortex component
    radius = np.sqrt(x**2 + y**2)
    # Avoid division by zero at origin
    radius[radius == 0] = 1e-5 
    
    # Velocity drops off with distance from center (Rankine-like vortex)
    vortex_strength = 5.0
    u_vortex = -vortex_strength * y / radius**2 * np.exp(-radius**2 / 2)
    v_vortex =  vortex_strength * x / radius**2 * np.exp(-radius**2 / 2)

    # Background wind component (blowing diagonally up-right)
    u_wind = np.ones_like(x) * 1.5
    v_wind = np.ones_like(y) * 1.0

    # Total initial velocity field
    u_initial = u_vortex + u_wind
    v_initial = v_vortex + v_wind

    # Advect the flow field forward in time by 0.5 seconds
    dt = 0.5
    u_final, v_final = advect_2d(x, y, u_initial, v_initial, dt)

    # --- Plotting ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    # Plot Initial State
    speed_initial = np.sqrt(u_initial**2 + v_initial**2)
    strm1 = ax1.streamplot(x, y, u_initial, v_initial, color=speed_initial, cmap='viridis')
    ax1.set_title("t = 0 (Initial Flow Field)")
    ax1.set_xlim(-3, 3); ax1.set_ylim(-3, 3)
    
    # Plot Final State
    speed_final = np.sqrt(u_final**2 + v_final**2)
    strm2 = ax2.streamplot(x, y, u_final, v_final, color=speed_final, cmap='viridis')
    ax2.set_title(f"t = {dt} (Advected Flow Field)")
    ax2.set_xlim(-3, 3); ax2.set_ylim(-3, 3)
    
    plt.tight_layout()
    plt.show()